name: SILE

on: [ push, pull_request ]

jobs:

  sile:
    strategy:
      fail-fast: false
      matrix:
        # Test oldest compatible release plus newest patch of each minor bump since
        sileVersion: [ "v0.13.0", "v0.13.3" ]
    runs-on: ubuntu-latest
    container:
      image: docker://siletypesetter/sile:${{ matrix.sileVersion }}
      options: --entrypoint=bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dictionary
      run: pacman --noconfirm -S words
    - name: Run test template
      run: sile fpTest.sil
#   Disabled because luasocket is acting up on Lua 5.4.3 and producing false failures
#   https://github.com/diegonehab/luasocket/issues/331
#   - name: Run gutenberg template
#     run: sile fpGutenberg.sil
    - name: Run unichar template
      run: sile fpUnichar.sil
    - name: Run full template
      run: sile fpFull.sil
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fp-templates.zip
        path: fp*.pdf
