name: SILE

on: [ push, pull_request ]

jobs:

  sile:
    strategy:
      fail-fast: false
      matrix:
        sileVersion: [ "v0.14.10" ]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sile-typesetter/sile:${{ matrix.sileVersion }}
      options: --entrypoint=bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dev dependencies
      run: pacman --noconfirm --needed -S luarocks make words
    - name: Build and install locally
      run: make install
    - name: Run test template
      run: ./lua_modules/bin/fontproof -t test -o test.pdf
    - name: Run gutenberg template
      run: ./lua_modules/bin/fontproof -t gutenberg -o gutenberg.pdf
    - name: Run unichar template
      run: ./lua_modules/bin/fontproof -t unichar -o unichar.pdf
    - name: Run full template
      run: ./lua_modules/bin/fontproof -t full -o full.pdf
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fp-template-tests.zip
        path: '*.pdf'
